### ISSUE TITLE
About menu reopening

### ISSUE THREAD

**Issue by Fire-wood** [monadgroup/axiom#26] opened 2018-06-10 01:03 UTC
Opening the About menu via F1 or the 'Help' button and then closing it causes another about menu to appear.

**Comment by cpdt** [comment] 2018-07-04 13:07
I haven't been able to replicate this - are you sure that's all you're doing?

**Comment by cpdt** [comment] 2018-07-15 12:46
Closing due to not being able to reproduce :)

**Closed by cpdt** 2018-07-15 12:46 UTC
Labels: bug, editor
