### ISSUE TITLE
Save Option

### ISSUE THREAD

**Issue by Fire-wood** [monadgroup/axiom#47] opened 2018-08-07 09:04 UTC
Currently, trying to save an open project will always prompt 'Save As' with no quick save. A 'Save' button in addition to 'Save As' would be beneficial (also updating the hotkey Ctrl + S to quick save).

**Comment by cpdt** [comment] 2018-08-07 09:05
Duplicate of #34

**Closed by cpdt** 2018-08-07 09:05 UTC
Labels: editor, enhancement
