### ISSUE TITLE
Lighten Background Contrast

### ISSUE THREAD

**Issue by Fire-wood** [monadgroup/axiom#13] opened 2018-06-08 08:21 UTC
With the current background, it's very difficult to identify the outlines of segments e.g. borders between windows, exit symbols of windows. A brighter contrast or background colour would be beneficial.

**Comment by cpdt** [comment] 2018-06-08 08:29
What do you mean by "segments"?

**Comment by cpdt** [comment] 2018-08-12 11:48
Going to mark this as a duplicate of #40 for now, since that's more inclusive of the rest of the UI (as opposed to just the background, which this is about).

**Closed by cpdt** 2018-08-12 11:48 UTC
Labels: editor, enhancement
